// Mocks generated by Mockito 5.3.2 from annotations
// in al_quran_apps/test/detail_surah_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:al_quran_apps/common/failure.dart' as _i6;
import 'package:al_quran_apps/domain/entities/detail_surah/detail_surah.dart'
    as _i7;
import 'package:al_quran_apps/domain/repositories/surah_repositories.dart'
    as _i2;
import 'package:al_quran_apps/domain/usecases/surah/get_detail_surah.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSurahRepository_0 extends _i1.SmartFake
    implements _i2.SurahRepository {
  _FakeSurahRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetDetailSurah].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDetailSurah extends _i1.Mock implements _i4.GetDetailSurah {
  MockGetDetailSurah() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SurahRepository get surahRepository => (super.noSuchMethod(
        Invocation.getter(#surahRepository),
        returnValue: _FakeSurahRepository_0(
          this,
          Invocation.getter(#surahRepository),
        ),
      ) as _i2.SurahRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.DetailSurah>> execute(int? number) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [number],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.DetailSurah>>.value(
            _FakeEither_1<_i6.Failure, _i7.DetailSurah>(
          this,
          Invocation.method(
            #execute,
            [number],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.DetailSurah>>);
}
